name: Release Tests

on:
  push:
    tags: "*"

env:
  RELEASE: 1
  artifact: 0

jobs:
  osx_test:
    name: OSX unit tests [TEST_USE_ROCKSDB=${{ matrix.TEST_USE_ROCKSDB }} - RELEASE=1]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        TEST_USE_ROCKSDB:
          - 1
          - 0
    runs-on: macos-latest
    env:
      BOOST_ROOT: /tmp/boost
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh
      - name: Build Tests
        env:
          TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
        run: ci/build-travis.sh "/tmp/qt/lib/cmake/Qt5";
      - name: Run Tests
        env:
          TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
        run: cd build && sudo cmake --build . --target run_tests -k

  gcc_test:
    name: Linux Unit Tests [TEST_USE_ROCKSDB=${{ matrix.TEST_USE_ROCKSDB }} - COMPILER=${{ matrix.COMPILER }} - RELEASE=1]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        TEST_USE_ROCKSDB:
          - 0
          - 1
        COMPILER:
          - gcc
          - clang-6
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - name: Fetch Deps
        env:
          COMPILER: ${{ matrix.COMPILER }}
        run: ci/actions/linux/install_deps.sh
      - name: Build Tests
        env:
          TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
        run: docker run -e RELEASE -e TEST_USE_ROCKSDB -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace && ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5"
      - name: Run Tests
        run: docker run -e RELEASE -e TEST_USE_ROCKSDB -v ${PWD}:/workspace nanocurrency/nano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && cmake --build . --target run_tests"

  windows_test:
    name: Windows Unit Tests [TEST_USE_ROCKSDB=${{ matrix.TEST_USE_ROCKSDB }} - RELEASE=1]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        TEST_USE_ROCKSDB:
          - 0
          - 1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1
      - name: Run Tests
        env:
          TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
        run: ci/actions/windows/build.ps1